// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

var MyLambdaFunction = require('../src/index.js'); // assumes single Lambda function with exports.handler

 // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
var event =
    {
        "session": {
            "sessionId": "SessionId.f5ef894d-e97a-4f72-88a3-62a893",
            "application": {
                "applicationId": "amzn1.ask.skill.9014c60c-44f2-4504-8251d33"
            },
            "attributes": {},
            "user": {
                "userId": "amzn1.ask.account.AGOSGOC2TIMVR35HGIK4QI2R7JSDVXR7ORFHV2YOHA63IF367QJ5RTWTAPEWAR5BWZJLZKBJG55D6CNBNVFSFQB5LGI4TNIJKIBOK44HMMJOHACFQOMWLAAHCEI46SI7XKUXGUTFR5KCILMKZSLIU2IT7VNWWF6JD6YMM7EBJFWAP25ZIW2Y"
            },
            "new": true
        },
        "request": {
            "type": "IntentRequest",
            "requestId": "EdwRequestId.b58878d6-b828-4193-805b-0e009",
            "locale": "de-DE",
            "timestamp": "2017-03-10T04:23:50Z",
            "intent": {
                "name": "CityIntent",
                "slots": {
                    "city": {
                        "name": "city",
                        "value": "Frankfurt"
                    }
                }
            }
        },
        "version": "1.0"
    };

var context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }

};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}

// call the function
MyLambdaFunction['handler'] (event, context, callback);
